## RCSBをキーワード検索してPDBのリストを作成

In [1]:
from pypdb import *
q = input('keywords? ')
pdb_ids = Query(q).search()
print('the number of PDB IDs are ' + str(len(pdb_ids)))

/Users/keetane/opt/anaconda3/envs/code/lib/python3.12/site-packages/pypdb/util/http_requests.py:65: UserWarning: Too many failures on requests. Exiting...
  warnings.warn("Too many failures on requests. Exiting...")
/Users/keetane/opt/anaconda3/envs/code/lib/python3.12/site-packages/pypdb/pypdb.py:303: UserWarning: Retrieval failed, returning None
  warnings.warn("Retrieval failed, returning None")

TypeError: object of type 'NoneType' has no len()

# UniprotKB accessionから情報を得る

In [3]:
keyword = input('UniprotKB? ')
# CRBN = Q96SW2
# RNF43 = Q68DV7
# WDR5 = P61964

In [ ]:
keys = [
    'Q96SW2', 
    'Q68DV7'
]

In [4]:
import pandas as pd
from Bio import SeqIO
from Bio.PDB import PDBList as pdbl
from urllib.request import urlopen

In [5]:
handle = urlopen("http://www.uniprot.org/uniprot/" + keyword + ".xml")
record = SeqIO.read(handle, "uniprot-xml")
# print(record)

In [8]:
dbx = record.dbxrefs
dfIO = pd.DataFrame(dbx)
df = dfIO[0].str.split(':', expand=True)
df.columns = ['name', 'id', 'and', 'or']
df

              name               id              and    or
0             ABCD           P61964             None  None
1              AGR             HGNC            12757  None
2      AlphaFoldDB           P61964             None  None
3    Antibodypedia            31978             None  None
4             Bgee  ENSG00000196363             None  None
..             ...              ...              ...   ...
531      VEuPathDB           HostDB  ENSG00000196363  None
532         eggNOG          KOG0266             None  None
533        iPTMnet           P61964             None  None
534          jPOST           P61964             None  None
535       neXtProt        NX_P61964             None  None

[536 rows x 4 columns]

In [15]:
PDBs = list(df[df['name']=='PDB']['id'])
print(f'the number of PDBs is {len(PDBs)}')

the number of PDBs is 156

In [16]:
PDBs

['2CNX',
 '2CO0',
 '2G99',
 '2G9A',
 '2GNQ',
 '2H13',
 '2H14',
 '2H68',
 '2H6K',
 '2H6N',
 '2H6Q',
 '2H9L',
 '2H9M',
 '2H9N',
 '2H9P',
 '2O9K',
 '3EG6',
 '3EMH',
 '3MXX',
 '3N0D',
 '3N0E',
 '3P4F',
 '3PSL',
 '3SMR',
 '3UR4',
 '3UVK',
 '3UVL',
 '3UVM',
 '3UVN',
 '3UVO',
 '4A7J',
 '4CY1',
 '4CY2',
 '4ERQ',
 '4ERY',
 '4ERZ',
 '4ES0',
 '4ESG',
 '4EWR',
 '4GM3',
 '4GM8',
 '4GM9',
 '4GMB',
 '4IA9',
 '4O45',
 '4QL1',
 '4Y7R',
 '5EAL',
 '5EAM',
 '5EAP',
 '5EAR',
 '5M23',
 '5M25',
 '5SXM',
 '5VFC',
 '6BYN',
 '6D9X',
 '6DAI',
 '6DAK',
 '6DAR',
 '6DAS',
 '6DY7',
 '6DYA',
 '6E1Y',
 '6E1Z',
 '6E22',
 '6E23',
 '6IAM',
 '6KIU',
 '6KIV',
 '6KIW',
 '6KIX',
 '6KIZ',
 '6OFZ',
 '6OI0',
 '6OI1',
 '6OI2',
 '6OI3',
 '6PG3',
 '6PG4',
 '6PG5',
 '6PG6',
 '6PG7',
 '6PG8',
 '6PG9',
 '6PGA',
 '6PGB',
 '6PGC',
 '6PGD',
 '6PGE',
 '6PGF',
 '6PWV',
 '6PWW',
 '6U5M',
 '6U5Y',
 '6U6W',
 '6U80',
 '6U8B',
 '6U8L',
 '6U8O',
 '6UCS',
 '6UFX',
 '6UHY',
 '6UHZ',
 '6UIF',
 '6UIK',
 '6UJ4',
 '6UJH',
 '6UJJ',
 '6UJL',
 '6UOZ',
 '6W5I',
 '6W5M',
 '6W5N',
 '6WJQ',
 '7AXP',
 '7AXQ',
 '7AXS',
 '7AXU',
 '7AXX',
 '7BCY',
 '7BED',
 '7CFP',
 '7CFQ',
 '7DNO',
 '7JTO',
 '7JTP',
 '7MBM',
 '7MBN',
 '7Q2J',
 '7U9Y',
 '7UAS',
 '7UD5',
 '7WVK',
 '8BB2',
 '8BB3',
 '8BB4',
 '8BB5',
 '8DU4',
 '8E9F',
 '8F1G',
 '8F93',
 '8G3C',
 '8G3E',
 '8HMX',
 '8Q1N',
 '8T5I',
 '8UJY',
 '8WXQ',
 '8WXR',
 '8WXT',
 '8WXU',
 '8WXV',
 '8WXX',
 '8X3R',
 '8X3S']

## PDBリストからリガンドを抜き出し、Supplier Listを作成

### 3 requests

In [17]:
%%timeit
import requests
import pubchempy as pcp
import pandas as pd

# Ligandの判定関数

def judge(entry_id):
    ligand_list = []
    query = '''
    {
    entry(entry_id:"''' + entry_id + '''") {
        nonpolymer_entities {
        rcsb_nonpolymer_entity_container_identifiers {
        entry_id
     }
    nonpolymer_comp {
        chem_comp {
        id
        type
        }
        pdbx_chem_comp_descriptor {
        descriptor
        type
        program
            }
        }
    }
    }
    }
    '''

    url = "https://data.rcsb.org/graphql?query=" + query
    response = requests.get(url)
    json_data = response.json()
    return(json_data['data']['entry']['nonpolymer_entities'])

# UNLやUNKの例外処理

def UNL_UNK(entry_id):
    ligand_list = []

    query = '''
    {
    entry(entry_id:"'''  + entry_id + '''") {
        nonpolymer_entities {
        rcsb_nonpolymer_entity_container_identifiers {
            entry_id
        }
        nonpolymer_comp {
            chem_comp {
            id
            type
            }
            pdbx_chem_comp_descriptor {
            descriptor
            type
            program
            }
        }
        }
    }
    }
    '''

    url = "https://data.rcsb.org/graphql?query=" + query
    response = requests.get(url)
    json_data = response.json()

    return(json_data['data']['entry']['nonpolymer_entities'][0]['nonpolymer_comp']['pdbx_chem_comp_descriptor'])

# PDB IDからリガンドリストを作成

def entry_to_ligand(entry_id):

    ligand_list = []
    query = '''
    {
    entry(entry_id:"'''  + entry_id + '''") {
      rcsb_id
    struct {
      title
    }
        nonpolymer_entities {
        rcsb_nonpolymer_entity_container_identifiers {
            entry_id
        }
        nonpolymer_comp {
            chem_comp {
            id
            type
            }
            pdbx_chem_comp_descriptor {
            descriptor
            type
            program
            }
        }
        }
    }
    }
    '''

    url = "https://data.rcsb.org/graphql?query=" + query
    response = requests.get(url)
    json_data = response.json()
    for i in json_data.get('data').get('entry').get('nonpolymer_entities'):
        entry_id = i.get('rcsb_nonpolymer_entity_container_identifiers')
        nonpolymer_comp = i.get('nonpolymer_comp')
        ligand_id = nonpolymer_comp.get('chem_comp').get('id')
        for data in nonpolymer_comp.get('pdbx_chem_comp_descriptor'):
            if (data.get('type') == "InChI") and (data.get('program') == "InChI"):
                inchi = [data.get('descriptor')]
                type = [data.get('type')]
                program = [data.get('program')]
                d = {'Ligand_ID':ligand_id, 'InChI':inchi}
                ligand_list.append(d)
            df = pd.DataFrame(ligand_list)
            df['Title'] = json_data['data']['entry']['struct']['title']
    return(df)

# ここからfor文

# pdb_ids = ['5UT2', '4FVR'] # for test
cols = ['Ligand_ID', 'SMILES', 'InChI', 'CID', 'MW', 'PDB_ID', 'Title', 'Supplier', 'RCSB_URL', 'Ligand_URL']
Sup_List = pd.DataFrame(columns = cols)

for pdb_id in PDBs:

    # Ligandがない場合の例外処理
    if judge(pdb_id) != None:
        if UNL_UNK(pdb_id) != None:

            # DataFrameの作成
            df = pd.DataFrame(entry_to_ligand(pdb_id))

            df['PDB_ID'] = pdb_id
            df['CID'] =  df['InChI'].map(lambda x : pcp.get_properties('MolecularWeight', x, 'inchi')[0]['CID']).astype(str)
            df['MW'] =  df['InChI'].map(lambda x : pcp.get_properties('MolecularWeight', x, 'inchi')[0]['MolecularWeight']).astype(float)
            df['SMILES'] =  df['InChI'].map(lambda x : pcp.get_properties('IsomericSMILES', x, 'inchi')[0]['IsomericSMILES'])
            df['Title'] =  df['PDB_ID'].map(lambda x : title(x))

            # リンクの作成
            df['Supplier'] = df['CID'].map(lambda x : 'https://pubchem.ncbi.nlm.nih.gov/compound/' + x + '#section=Chemical-Vendors&fullscreen=true')
            df['RCSB_URL'] = df['PDB_ID'].map(lambda x : 'https://www.rcsb.org/structure/' + x)
            df['Ligand_URL'] = df['Ligand_ID'].map(lambda x : 'https://www.rcsb.org/ligand/' + x)
            # df['Title'] = json_data['data']['entry']['struct']['title']

            # df結合
            Sup_List = pd.concat([Sup_List, df])
        else:
            df = pd.DataFrame(columns=cols)
            empty = []
            empty.append(pdb_id)
            df['PDB_ID'] = empty
            df['RCSB_URL'].iloc[0] =  'https://www.rcsb.org/structure/' + pdb_id
        Sup_List = pd.concat([Sup_List, df])
    else:
        df = pd.DataFrame(columns=cols)
        empty = []
        empty.append(pdb_id)
        df['PDB_ID'] = empty
        df['RCSB_URL'].iloc[0] =  'https://www.rcsb.org/structure/' + pdb_id
        Sup_List = pd.concat([Sup_List, df])

Sup_List = Sup_List.reset_index(drop=True)
Sup_List

<magic-timeit>:162: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

<magic-timeit>:162: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

<magic-timeit>:162: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

<magic-timeit>:162: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Users/keetane/opt/anaconda3/envs/code/lib/python3.12/site-packages/executing/executing.py:713: DeprecationWarning: ast.Str is deprecated and will be removed in Python 3.14; use ast.Constant instead
  right=ast.Str(s=sentinel),
/Users/keetane/opt/anaconda3/envs/code/lib/python3.12/ast.py:587: DeprecationWarning: Attribute s is deprecated and will be removed in Python 3.14; use value instead
  return Constant(*args, **kwargs)
/Users/keetane/opt/anaconda3/envs/code/lib/python3.12/site-packages/executing/executing.py:713: DeprecationWarning: ast.Str is deprecated and will be removed in Python 3.14; use ast.Constant instead
  right=ast.Str(s=sentinel),
/Users/keetane/opt/anaconda3/envs/code/lib/python3.12/ast.py:587: DeprecationWarning: Attribute s is deprecated and will be removed in Python 3.14; use value instead
  return Constant(*args, **kwargs)

NameError: name 'title' is not defined

### 1 request

In [22]:
%%timeit
import requests
import pubchempy as pcp
import pandas as pd
import json

def fetch_nonpolymer_entities(entry_id):
    query = '''
    {
    entry(entry_id:"''' + entry_id + '''") {
        nonpolymer_entities {
        rcsb_nonpolymer_entity_container_identifiers {
        entry_id
     }
    nonpolymer_comp {
        chem_comp {
        id
        type
        }
        pdbx_chem_comp_descriptor {
        descriptor
        type
        program
            }
        }
    }
    }
    }
    '''

    url = "https://data.rcsb.org/graphql?query=" + query
    response = requests.get(url)
    json_data = response.json()
    return json_data['data']['entry']['nonpolymer_entities']

# Ligandの有無を判定してdfを作成する関数

def judge(entry_id):
    return fetch_nonpolymer_entities(entry_id)

def UNL_UNK(entry_id):
    nonpolymer_entities = fetch_nonpolymer_entities(entry_id)
    return nonpolymer_entities[0]['nonpolymer_comp']['pdbx_chem_comp_descriptor']

def entry_to_ligand(entry_id):
    nonpolymer_entities = fetch_nonpolymer_entities(entry_id)
    ligand_data = []
    for entity in nonpolymer_entities:
        for comp in entity['nonpolymer_comp']:
            ligand_data.append({
                'Ligand_ID': comp['chem_comp']['id'],
                'SMILES': comp['pdbx_chem_comp_descriptor'][0]['descriptor'] if comp['pdbx_chem_comp_descriptor'] else None,
                'InChI': comp['pdbx_chem_comp_descriptor'][1]['descriptor'] if len(comp['pdbx_chem_comp_descriptor']) > 1 else None
            })
    return pd.DataFrame(ligand_data)

# ここからfor文

# pdb_ids = ['5UT2', '4FVR'] # for test
cols = ['Ligand_ID', 'SMILES', 'InChI', 'CID', 'MW', 'PDB_ID', 'Title', 'Supplier', 'RCSB_URL', 'Ligand_URL']
Sup_List = pd.DataFrame(columns = cols)

for pdb_id in PDBs:

    # Ligandがない場合の例外処理
    if judge(pdb_id) != None:
        if UNL_UNK(pdb_id) != None:

            # DataFrameの作成
            df = pd.DataFrame(entry_to_ligand(pdb_id))

            df['PDB_ID'] = pdb_id
            df['CID'] =  df['InChI'].map(lambda x : pcp.get_properties('MolecularWeight', x, 'inchi')[0]['CID']).astype(str)
            df['MW'] =  df['InChI'].map(lambda x : pcp.get_properties('MolecularWeight', x, 'inchi')[0]['MolecularWeight']).astype(float)
            df['SMILES'] =  df['InChI'].map(lambda x : pcp.get_properties('IsomericSMILES', x, 'inchi')[0]['IsomericSMILES'])
            df['Title'] =  df['PDB_ID'].map(lambda x : title(x))

            # リンクの作成
            df['Supplier'] = df['CID'].map(lambda x : 'https://pubchem.ncbi.nlm.nih.gov/compound/' + x + '#section=Chemical-Vendors&fullscreen=true')
            df['RCSB_URL'] = df['PDB_ID'].map(lambda x : 'https://www.rcsb.org/structure/' + x)
            df['Ligand_URL'] = df['Ligand_ID'].map(lambda x : 'https://www.rcsb.org/ligand/' + x)
            # df['Title'] = json_data['data']['entry']['struct']['title']

            # df結合
            Sup_List = pd.concat([Sup_List, df])
        else:
            df = pd.DataFrame(columns=cols)
            empty = []
            empty.append(pdb_id)
            df['PDB_ID'] = empty
            df['RCSB_URL'].iloc[0] =  'https://www.rcsb.org/structure/' + pdb_id
        Sup_List = pd.concat([Sup_List, df])
    else:
        df = pd.DataFrame(columns=cols)
        empty = []
        empty.append(pdb_id)
        df['PDB_ID'] = empty
        df['RCSB_URL'].iloc[0] =  'https://www.rcsb.org/structure/' + pdb_id
        Sup_List = pd.concat([Sup_List, df])

Sup_List = Sup_List.reset_index(drop=True)

<magic-timeit>:97: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

<magic-timeit>:97: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

<magic-timeit>:97: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

<magic-timeit>:97: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

TypeError: string indices must be integers, not 'str'

## MW > 150でfiltering

In [208]:
Sup_List_150 =  Sup_List[Sup_List['MW']>150].reset_index(drop=True)
Sup_List_150

,Ligand_ID,SMILES,InChI,CID,MW,PDB_ID,Title,Supplier,RCSB_URL,Ligand_URL
0,MES,C1COCCN1CCS(=O)(=O)O,"[InChI=1S/C6H13NO4S/c8-12(9,10)6-3-7-1-4-11-5-...",78165,195.24,4A08,Structure of hsDDB1-drDDB2 bound to a 13 bp CP...,https://pubchem.ncbi.nlm.nih.gov/compound/7816...,https://www.rcsb.org/structure/4A08,https://www.rcsb.org/ligand/MES
1,MES,C1COCCN1CCS(=O)(=O)O,"[InChI=1S/C6H13NO4S/c8-12(9,10)6-3-7-1-4-11-5-...",78165,195.24,4A08,Structure of hsDDB1-drDDB2 bound to a 13 bp CP...,https://pubchem.ncbi.nlm.nih.gov/compound/7816...,https://www.rcsb.org/structure/4A08,https://www.rcsb.org/ligand/MES
2,EF2,C1CC(=O)NC(=O)[C@H]1N2C(=O)C3=CC=CC=C3C2=O,[InChI=1S/C13H10N2O4/c16-10-6-5-9(11(17)14-10)...,92142,258.23,4TZC,Crystal Structure of Murine Cereblon in Comple...,https://pubchem.ncbi.nlm.nih.gov/compound/9214...,https://www.rcsb.org/structure/4TZC,https://www.rcsb.org/ligand/EF2
3,EF2,C1CC(=O)NC(=O)[C@H]1N2C(=O)C3=CC=CC=C3C2=O,[InChI=1S/C13H10N2O4/c16-10-6-5-9(11(17)14-10)...,92142,258.23,4TZC,Crystal Structure of Murine Cereblon in Comple...,https://pubchem.ncbi.nlm.nih.gov/compound/9214...,https://www.rcsb.org/structure/4TZC,https://www.rcsb.org/ligand/EF2

## Duplicateを除去

In [209]:
Sup_List_Dup = Sup_List[Sup_List['MW']>150].drop_duplicates('Ligand_ID').reset_index(drop=True)
Sup_List_Dup

,Ligand_ID,SMILES,InChI,CID,MW,PDB_ID,Title,Supplier,RCSB_URL,Ligand_URL
0,MES,C1COCCN1CCS(=O)(=O)O,"[InChI=1S/C6H13NO4S/c8-12(9,10)6-3-7-1-4-11-5-...",78165,195.24,4A08,Structure of hsDDB1-drDDB2 bound to a 13 bp CP...,https://pubchem.ncbi.nlm.nih.gov/compound/7816...,https://www.rcsb.org/structure/4A08,https://www.rcsb.org/ligand/MES
1,EF2,C1CC(=O)NC(=O)[C@H]1N2C(=O)C3=CC=CC=C3C2=O,[InChI=1S/C13H10N2O4/c16-10-6-5-9(11(17)14-10)...,92142,258.23,4TZC,Crystal Structure of Murine Cereblon in Comple...,https://pubchem.ncbi.nlm.nih.gov/compound/9214...,https://www.rcsb.org/structure/4TZC,https://www.rcsb.org/ligand/EF2

In [184]:
import requests
import pubchempy as pcp
import pandas as pd

# Ligandの判定関数

def judge(entry_id):
    ligand_list = []
    query = '''
    {
    entry(entry_id:"''' + entry_id + '''") {
        nonpolymer_entities {
        rcsb_nonpolymer_entity_container_identifiers {
        entry_id
     }
    nonpolymer_comp {
        chem_comp {
        id
        type
        }
        pdbx_chem_comp_descriptor {
        descriptor
        type
        program
            }
        }
    }
    }
    }
    '''

    url = "https://data.rcsb.org/graphql?query=" + query
    response = requests.get(url)
    json_data = response.json()
    return(json_data['data']['entry']['nonpolymer_entities'])

# UNLやUNKの例外処理

def UNL_UNK(entry_id):
    ligand_list = []

    query = '''
    {
    entry(entry_id:"'''  + entry_id + '''") {
        nonpolymer_entities {
        rcsb_nonpolymer_entity_container_identifiers {
            entry_id
        }
        nonpolymer_comp {
            chem_comp {
            id
            type
            }
            pdbx_chem_comp_descriptor {
            descriptor
            type
            program
            }
        }
        }
    }
    }
    '''

    url = "https://data.rcsb.org/graphql?query=" + query
    response = requests.get(url)
    json_data = response.json()

    return(json_data['data']['entry']['nonpolymer_entities'][0]['nonpolymer_comp']['pdbx_chem_comp_descriptor'])

# PDB IDからリガンドリストを作成

def entry_to_ligand(entry_id):

    ligand_list = []
    query = '''
    {
    entry(entry_id:"'''  + entry_id + '''") {
      rcsb_id
    struct {
      title
    }
        nonpolymer_entities {
        rcsb_nonpolymer_entity_container_identifiers {
            entry_id
        }
        nonpolymer_comp {
            chem_comp {
            id
            type
            }
            pdbx_chem_comp_descriptor {
            descriptor
            type
            program
            }
        }
        }
    }
    }
    '''

    url = "https://data.rcsb.org/graphql?query=" + query
    response = requests.get(url)
    json_data = response.json()
    for i in json_data.get('data').get('entry').get('nonpolymer_entities'):
        entry_id = i.get('rcsb_nonpolymer_entity_container_identifiers')
        nonpolymer_comp = i.get('nonpolymer_comp')
        ligand_id = nonpolymer_comp.get('chem_comp').get('id')
        for data in nonpolymer_comp.get('pdbx_chem_comp_descriptor'):
            if (data.get('type') == "InChI") and (data.get('program') == "InChI"):
                inchi = [data.get('descriptor')]
                type = [data.get('type')]
                program = [data.get('program')]
                d = {'Ligand_ID':ligand_id, 'InChI':inchi}
                ligand_list.append(d)
            df = pd.DataFrame(ligand_list)
            df['Title'] = json_data['data']['entry']['struct']['title']
    return(df)

# ここからfor文

pdb_list = ['5UT2', '4FVR']
cols = ['Ligand_ID', 'SMILES', 'InChI', 'CID', 'MW', 'PDB_ID', 'Title', 'Supplier', 'RCSB_URL', 'Ligand_URL']
Sup_List = pd.DataFrame(columns = cols)

for pdb_id in pdb_list:

    # Ligandがない場合の例外処理
    if judge(pdb_id) != None:
        if UNL_UNK(pdb_id) != None:

            # DataFrameの作成
            df = pd.DataFrame(entry_to_ligand(pdb_id))

            df['PDB_ID'] = pdb_id
            df['CID'] =  df['InChI'].map(lambda x : pcp.get_properties('MolecularWeight', x, 'inchi')[0]['CID']).astype(str)
            df['MW'] =  df['InChI'].map(lambda x : pcp.get_properties('MolecularWeight', x, 'inchi')[0]['MolecularWeight']).astype(float)
            df['SMILES'] =  df['InChI'].map(lambda x : pcp.get_properties('IsomericSMILES', x, 'inchi')[0]['IsomericSMILES'])
            df['Title'] =  df['PDB_ID'].map(lambda x : title(x))

            # リンクの作成
            df['Supplier'] = df['CID'].map(lambda x : 'https://pubchem.ncbi.nlm.nih.gov/compound/' + x + '#section=Chemical-Vendors&fullscreen=true')
            df['RCSB_URL'] = df['PDB_ID'].map(lambda x : 'https://www.rcsb.org/structure/' + x)
            df['Ligand_URL'] = df['Ligand_ID'].map(lambda x : 'https://www.rcsb.org/ligand/' + x)
            # df['Title'] = json_data['data']['entry']['struct']['title']

            # df結合
            Sup_List = pd.concat([Sup_List, df])
        else:
            df = pd.DataFrame(columns=cols)
            empty = []
            empty.append(pdb_id)
            df['PDB_ID'] = empty
            df['RCSB_URL'].iloc[0] =  'https://www.rcsb.org/structure/' + pdb_id
        Sup_List = pd.concat([Sup_List, df])
    else:
        df = pd.DataFrame(columns=cols)
        empty = []
        empty.append(pdb_id)
        df['PDB_ID'] = empty
        df['RCSB_URL'].iloc[0] =  'https://www.rcsb.org/structure/' + pdb_id
        Sup_List = pd.concat([Sup_List, df])

Sup_List = Sup_List.reset_index(drop=True)

In [194]:
Sup_List

,Ligand_ID,SMILES,InChI,CID,MW,PDB_ID,Title,Supplier,RCSB_URL,Ligand_URL
0,GOL,C(C(CO)O)O,"[InChI=1S/C3H8O3/c4-1-3(6)2-5/h3-6H,1-2H2]",753,92.090,5UT2,JAK2 JH2 in complex with PRT062607,https://pubchem.ncbi.nlm.nih.gov/compound/753#...,https://www.rcsb.org/structure/5UT2,https://www.rcsb.org/ligand/GOL
1,3YT,C1CC[C@H]([C@H](C1)N)NC2=NC=C(C(=N2)NC3=CC(=CC...,[InChI=1S/C19H23N9O/c20-15-6-1-2-7-16(15)26-19...,44462758,393.400,5UT2,JAK2 JH2 in complex with PRT062607,https://pubchem.ncbi.nlm.nih.gov/compound/4446...,https://www.rcsb.org/structure/5UT2,https://www.rcsb.org/ligand/3YT
2,ACT,CC(=O)[O-],"[InChI=1S/C2H4O2/c1-2(3)4/h1H3,(H,3,4)/p-1]",175,59.040,5UT2,JAK2 JH2 in complex with PRT062607,https://pubchem.ncbi.nlm.nih.gov/compound/175#...,https://www.rcsb.org/structure/5UT2,https://www.rcsb.org/ligand/ACT
3,GOL,C(C(CO)O)O,"[InChI=1S/C3H8O3/c4-1-3(6)2-5/h3-6H,1-2H2]",753,92.090,5UT2,JAK2 JH2 in complex with PRT062607,https://pubchem.ncbi.nlm.nih.gov/compound/753#...,https://www.rcsb.org/structure/5UT2,https://www.rcsb.org/ligand/GOL
4,3YT,C1CC[C@H]([C@H](C1)N)NC2=NC=C(C(=N2)NC3=CC(=CC...,[InChI=1S/C19H23N9O/c20-15-6-1-2-7-16(15)26-19...,44462758,393.400,5UT2,JAK2 JH2 in complex with PRT062607,https://pubchem.ncbi.nlm.nih.gov/compound/4446...,https://www.rcsb.org/structure/5UT2,https://www.rcsb.org/ligand/3YT
5,ACT,CC(=O)[O-],"[InChI=1S/C2H4O2/c1-2(3)4/h1H3,(H,3,4)/p-1]",175,59.040,5UT2,JAK2 JH2 in complex with PRT062607,https://pubchem.ncbi.nlm.nih.gov/compound/175#...,https://www.rcsb.org/structure/5UT2,https://www.rcsb.org/ligand/ACT
6,ATP,C1=NC(=C2C(=N1)N(C=N2)[C@H]3[C@@H]([C@@H]([C@H...,[InChI=1S/C10H16N5O13P3/c11-8-5-9(13-2-12-8)15...,5957,507.180,4FVR,Crystal structure of the Jak2 pseudokinase dom...,https://pubchem.ncbi.nlm.nih.gov/compound/5957...,https://www.rcsb.org/structure/4FVR,https://www.rcsb.org/ligand/ATP
7,MG,[Mg+2],[InChI=1S/Mg/q+2],888,24.305,4FVR,Crystal structure of the Jak2 pseudokinase dom...,https://pubchem.ncbi.nlm.nih.gov/compound/888#...,https://www.rcsb.org/structure/4FVR,https://www.rcsb.org/ligand/MG
8,ATP,C1=NC(=C2C(=N1)N(C=N2)[C@H]3[C@@H]([C@@H]([C@H...,[InChI=1S/C10H16N5O13P3/c11-8-5-9(13-2-12-8)15...,5957,507.180,4FVR,Crystal structure of the Jak2 pseudokinase dom...,https://pubchem.ncbi.nlm.nih.gov/compound/5957...,https://www.rcsb.org/structure/4FVR,https://www.rcsb.org/ligand/ATP
9,MG,[Mg+2],[InChI=1S/Mg/q+2],888,24.305,4FVR,Crystal structure of the Jak2 pseudokinase dom...,https://pubchem.ncbi.nlm.nih.gov/compound/888#...,https://www.rcsb.org/structure/4FVR,https://www.rcsb.org/ligand/MG

In [183]:
entry_to_ligand('5UT2')

,Ligand_ID,InChI,Title
0,GOL,"[InChI=1S/C3H8O3/c4-1-3(6)2-5/h3-6H,1-2H2]",JAK2 JH2 in complex with PRT062607
1,3YT,[InChI=1S/C19H23N9O/c20-15-6-1-2-7-16(15)26-19...,JAK2 JH2 in complex with PRT062607
2,ACT,"[InChI=1S/C2H4O2/c1-2(3)4/h1H3,(H,3,4)/p-1]",JAK2 JH2 in complex with PRT062607

In [97]:
import requests

query = '''
{
  entry(entry_id:"1AZ1") {
    nonpolymer_entities {
      rcsb_nonpolymer_entity_container_identifiers {
        entry_id
      }
      nonpolymer_comp {
        chem_comp {
          id
          type
        }
        pdbx_chem_comp_descriptor {
          descriptor
          type
          program
        }
      }
    }
  }
}
'''

url = "https://data.rcsb.org/graphql?query=" + query
response = requests.get(url)
json_data = response.json()
json_data
# json_data['data']['entry']['nonpolymer_entities'][1]#.keys()

{'data': {'entry': {'nonpolymer_entities': [{'rcsb_nonpolymer_entity_container_identifiers': {'entry_id': '1AZ1'},
     'nonpolymer_comp': {'chem_comp': {'id': 'NAP', 'type': 'non-polymer'},
      'pdbx_chem_comp_descriptor': [{'descriptor': 'NC(=O)c1ccc[n+](c1)[C@@H]2O[C@H](CO[P]([O-])(=O)O[P@@](O)(=O)OC[C@H]3O[C@H]([C@H](O[P](O)(O)=O)[C@@H]3O)n4cnc5c(N)ncnc45)[C@@H](O)[C@H]2O',
        'type': 'SMILES_CANONICAL',
        'program': 'CACTVS'},
       {'descriptor': 'NC(=O)c1ccc[n+](c1)[CH]2O[CH](CO[P]([O-])(=O)O[P](O)(=O)OC[CH]3O[CH]([CH](O[P](O)(O)=O)[CH]3O)n4cnc5c(N)ncnc45)[CH](O)[CH]2O',
        'type': 'SMILES',
        'program': 'CACTVS'},
       {'descriptor': 'c1cc(c[n+](c1)[C@H]2[C@@H]([C@@H]([C@H](O2)CO[P@@](=O)([O-])O[P@](=O)(O)OC[C@@H]3[C@H]([C@H]([C@@H](O3)n4cnc5c4ncnc5N)OP(=O)(O)O)O)O)O)C(=O)N',
        'type': 'SMILES_CANONICAL',
        'program': 'OpenEye OEToolkits'},
       {'descriptor': 'c1cc(c[n+](c1)C2C(C(C(O2)COP(=O)([O-])OP(=O)(O)OCC3C(C(C(O3)n4cnc5c4ncnc5N)OP(=O)(O)O)O)O)O)C(=O)N',
        'type': 'SMILES',
        'program': 'OpenEye OEToolkits'},
       {'descriptor': 'InChI=1S/C21H28N7O17P3/c22-17-12-19(25-7-24-17)28(8-26-12)21-16(44-46(33,34)35)14(30)11(43-21)6-41-48(38,39)45-47(36,37)40-5-10-13(29)15(31)20(42-10)27-3-1-2-9(4-27)18(23)32/h1-4,7-8,10-11,13-16,20-21,29-31H,5-6H2,(H7-,22,23,24,25,32,33,34,35,36,37,38,39)/t10-,11-,13-,14-,15-,16-,20-,21-/m1/s1',
        'type': 'InChI',
        'program': 'InChI'},
       {'descriptor': 'XJLXINKUBYWONI-NNYOXOHSSA-N',
        'type': 'InChIKey',
        'program': 'InChI'}]}},
    {'rcsb_nonpolymer_entity_container_identifiers': {'entry_id': '1AZ1'},
     'nonpolymer_comp': {'chem_comp': {'id': 'ALR', 'type': 'non-polymer'},
      'pdbx_chem_comp_descriptor': [{'descriptor': 'O=C2c1c3c(ccc1)cccc3C(=O)N2CC(=O)O',
        'type': 'SMILES',
        'program': 'ACDLabs'},
       {'descriptor': 'OC(=O)CN1C(=O)c2cccc3cccc(C1=O)c23',
        'type': 'SMILES_CANONICAL',
        'program': 'CACTVS'},
       {'descriptor': 'OC(=O)CN1C(=O)c2cccc3cccc(C1=O)c23',
        'type': 'SMILES',
        'program': 'CACTVS'},
       {'descriptor': 'c1cc2cccc3c2c(c1)C(=O)N(C3=O)CC(=O)O',
        'type': 'SMILES_CANONICAL',
        'program': 'OpenEye OEToolkits'},
       {'descriptor': 'c1cc2cccc3c2c(c1)C(=O)N(C3=O)CC(=O)O',
        'type': 'SMILES',
        'program': 'OpenEye OEToolkits'},
       {'descriptor': 'InChI=1S/C14H9NO4/c16-11(17)7-15-13(18)9-5-1-3-8-4-2-6-10(12(8)9)14(15)19/h1-6H,7H2,(H,16,17)',
        'type': 'InChI',
        'program': 'InChI'},
       {'descriptor': 'GCUCIFQCGJIRNT-UHFFFAOYSA-N',
        'type': 'InChIKey',
        'program': 'InChI'}]}}]}}}

In [ ]:
import requests
import pubchempy as pcp
import pandas as pd

# Ligandの判定関数

def judge(entry_id):
    ligand_list = []
    query = '''
    {
    entry(entry_id:"''' + entry_id + '''") {
        nonpolymer_entities {
        rcsb_nonpolymer_entity_container_identifiers {
        entry_id
     }
    nonpolymer_comp {
        chem_comp {
        id
        type
        }
        pdbx_chem_comp_descriptor {
        descriptor
        type
        program
            }
        }
    }
    }
    }
    '''

    url = "https://data.rcsb.org/graphql?query=" + query
    response = requests.get(url)
    json_data = response.json()
    return(json_data['data']['entry']['nonpolymer_entities'])

# UNLやUNKの例外処理

def UNL_UNK(entry_id):
    ligand_list = []

    query = '''
    {
    entry(entry_id:"'''  + entry_id + '''") {
        nonpolymer_entities {
        rcsb_nonpolymer_entity_container_identifiers {
            entry_id
        }
        nonpolymer_comp {
            chem_comp {
            id
            type
            }
            pdbx_chem_comp_descriptor {
            descriptor
            type
            program
            }
        }
        }
    }
    }
    '''

    url = "https://data.rcsb.org/graphql?query=" + query
    response = requests.get(url)
    json_data = response.json()

    return(json_data['data']['entry']['nonpolymer_entities'][0]['nonpolymer_comp']['pdbx_chem_comp_descriptor'])

# PDB IDからリガンドリストを作成

def entry_to_ligand(entry_id):

    ligand_list = []
    query = '''
    {
    entry(entry_id:"'''  + entry_id + '''") {
      rcsb_id
    struct {
      title
    }
        nonpolymer_entities {
        rcsb_nonpolymer_entity_container_identifiers {
            entry_id
        }
        nonpolymer_comp {
            chem_comp {
            id
            type
            }
            pdbx_chem_comp_descriptor {
            descriptor
            type
            program
            }
        }
        }
    }
    }
    '''

    url = "https://data.rcsb.org/graphql?query=" + query
    response = requests.get(url)
    json_data = response.json()
    for i in json_data.get('data').get('entry').get('nonpolymer_entities'):
        entry_id = i.get('rcsb_nonpolymer_entity_container_identifiers')
        nonpolymer_comp = i.get('nonpolymer_comp')
        ligand_id = nonpolymer_comp.get('chem_comp').get('id')
        for data in nonpolymer_comp.get('pdbx_chem_comp_descriptor'):
            if (data.get('type') == "InChI") and (data.get('program') == "InChI"):
                inchi = [data.get('descriptor')]
                type = [data.get('type')]
                program = [data.get('program')]
                d = {'Ligand_ID':ligand_id, 'InChI':inchi}
                ligand_list.append(d)
            df = pd.DataFrame(ligand_list)
            df['Title'] = json_data['data']['entry']['struct']['title']
    return(df)

# ここからfor文

pdb_list = ['5UT2', '4FVR']
cols = ['Ligand_ID', 'SMILES', 'InChI', 'CID', 'MW', 'PDB_ID', 'Title', 'Supplier', 'RCSB_URL', 'Ligand_URL']
Sup_List = pd.DataFrame(columns = cols)

for pdb_id in pdb_list:

    # Ligandがない場合の例外処理
    if judge(pdb_id) != None:
        if UNL_UNK(pdb_id) != None:

            # DataFrameの作成
            df = pd.DataFrame(entry_to_ligand(pdb_id))

            df['PDB_ID'] = pdb_id
            df['CID'] =  df['InChI'].map(lambda x : pcp.get_properties('MolecularWeight', x, 'inchi')[0]['CID']).astype(str)
            df['MW'] =  df['InChI'].map(lambda x : pcp.get_properties('MolecularWeight', x, 'inchi')[0]['MolecularWeight']).astype(float)
            df['SMILES'] =  df['InChI'].map(lambda x : pcp.get_properties('IsomericSMILES', x, 'inchi')[0]['IsomericSMILES'])
            df['Title'] =  df['PDB_ID'].map(lambda x : title(x))

            # リンクの作成
            df['Supplier'] = df['CID'].map(lambda x : 'https://pubchem.ncbi.nlm.nih.gov/compound/' + x + '#section=Chemical-Vendors&fullscreen=true')
            df['RCSB_URL'] = df['PDB_ID'].map(lambda x : 'https://www.rcsb.org/structure/' + x)
            df['Ligand_URL'] = df['Ligand_ID'].map(lambda x : 'https://www.rcsb.org/ligand/' + x)
            # df['Title'] = json_data['data']['entry']['struct']['title']

            # df結合
            Sup_List = pd.concat([Sup_List, df])
        else:
            df = pd.DataFrame(columns=cols)
            empty = []
            empty.append(pdb_id)
            df['PDB_ID'] = empty
            df['RCSB_URL'].iloc[0] =  'https://www.rcsb.org/structure/' + pdb_id
        Sup_List = pd.concat([Sup_List, df])
    else:
        df = pd.DataFrame(columns=cols)
        empty = []
        empty.append(pdb_id)
        df['PDB_ID'] = empty
        df['RCSB_URL'].iloc[0] =  'https://www.rcsb.org/structure/' + pdb_id
        Sup_List = pd.concat([Sup_List, df])

Sup_List = Sup_List.reset_index(drop=True)

In [192]:
def PDB2L(entry_id):
    ligand_list = []

    query = '''
    {
    entry(entry_id:"'''  + entry_id + '''") {
      rcsb_id
    struct {
      title
    }
        nonpolymer_entities {
        rcsb_nonpolymer_entity_container_identifiers {
            entry_id
        }
        nonpolymer_comp {
            chem_comp {
            id
            type
            }
            pdbx_chem_comp_descriptor {
            descriptor
            type
            program
            }
        }
        }
    }
    }
    '''

    url = "https://data.rcsb.org/graphql?query=" + query
    response = requests.get(url)
    json_data = response.json()

    # dfの作成
    # Ligandがある場合だけrun
    if json_data['data']['entry']['nonpolymer_entities'] != None:
        # LigandがUNLやUNKではない時はrun
        if json_data['data']['entry']['nonpolymer_entities'][0]['nonpolymer_comp']['pdbx_chem_comp_descriptor'] != None:
            # 複数のリガンドをdfに代入
            for i in json_data.get('data').get('entry').get('nonpolymer_entities'):
                entry_id = i.get('rcsb_nonpolymer_entity_container_identifiers')
                nonpolymer_comp = i.get('nonpolymer_comp')
                ligand_id = nonpolymer_comp.get('chem_comp').get('id')
                for data in nonpolymer_comp.get('pdbx_chem_comp_descriptor'):
                    if (data.get('type') == "InChI") and (data.get('program') == "InChI"):
                        inchi = [data.get('descriptor')]
                        type = [data.get('type')]
                        program = [data.get('program')]
                        d = {'Ligand_ID':ligand_id, 'InChI':inchi}
                        ligand_list.append(d)
                    df = pd.DataFrame(ligand_list)
                    df['Title'] = json_data['data']['entry']['struct']['title']
        return(df)
PDB2L('4A0B')

In [193]:
import requests
import pubchempy as pcp
import pandas as pd

# Ligandの有無を判定してdfを作成する関数

def PDB2L(entry_id):
    ligand_list = []

    query = '''
    {
    entry(entry_id:"'''  + entry_id + '''") {
      rcsb_id
    struct {
      title
    }
        nonpolymer_entities {
        rcsb_nonpolymer_entity_container_identifiers {
            entry_id
        }
        nonpolymer_comp {
            chem_comp {
            id
            type
            }
            pdbx_chem_comp_descriptor {
            descriptor
            type
            program
            }
        }
        }
    }
    }
    '''

    url = "https://data.rcsb.org/graphql?query=" + query
    response = requests.get(url)
    json_data = response.json()

    # dfの作成
    # Ligandがある場合だけrun
    if json_data['data']['entry']['nonpolymer_entities'] != None:
        # LigandがUNLやUNKではない時はrun
        if json_data['data']['entry']['nonpolymer_entities'][0]['nonpolymer_comp']['pdbx_chem_comp_descriptor'] != None:
            # 複数のリガンドをdfに代入
            for i in json_data.get('data').get('entry').get('nonpolymer_entities'):
                entry_id = i.get('rcsb_nonpolymer_entity_container_identifiers')
                nonpolymer_comp = i.get('nonpolymer_comp')
                ligand_id = nonpolymer_comp.get('chem_comp').get('id')
                for data in nonpolymer_comp.get('pdbx_chem_comp_descriptor'):
                    if (data.get('type') == "InChI") and (data.get('program') == "InChI"):
                        inchi = [data.get('descriptor')]
                        type = [data.get('type')]
                        program = [data.get('program')]
                        d = {'Ligand_ID':ligand_id, 'InChI':inchi}
                        ligand_list.append(d)
                    df = pd.DataFrame(ligand_list)
                    df['Title'] = json_data['data']['entry']['struct']['title']
        return(df)

# ここからfor文

pdb_list = ['5UT2', '4FVR']
cols = ['Ligand_ID', 'SMILES', 'InChI', 'CID', 'MW', 'PDB_ID', 'Title', 'Supplier', 'RCSB_URL', 'Ligand_URL']
Sup_List = pd.DataFrame(columns = cols)

for pdb_id in pdb_list:

    # Ligandがない場合の例外処理
    if judge(pdb_id) != None:
        if UNL_UNK(pdb_id) != None:

            # DataFrameの作成
            df = pd.DataFrame(entry_to_ligand(pdb_id))

            df['PDB_ID'] = pdb_id
            df['CID'] =  df['InChI'].map(lambda x : pcp.get_properties('MolecularWeight', x, 'inchi')[0]['CID']).astype(str)
            df['MW'] =  df['InChI'].map(lambda x : pcp.get_properties('MolecularWeight', x, 'inchi')[0]['MolecularWeight']).astype(float)
            df['SMILES'] =  df['InChI'].map(lambda x : pcp.get_properties('IsomericSMILES', x, 'inchi')[0]['IsomericSMILES'])
            df['Title'] =  df['PDB_ID'].map(lambda x : title(x))

            # リンクの作成
            df['Supplier'] = df['CID'].map(lambda x : 'https://pubchem.ncbi.nlm.nih.gov/compound/' + x + '#section=Chemical-Vendors&fullscreen=true')
            df['RCSB_URL'] = df['PDB_ID'].map(lambda x : 'https://www.rcsb.org/structure/' + x)
            df['Ligand_URL'] = df['Ligand_ID'].map(lambda x : 'https://www.rcsb.org/ligand/' + x)
            # df['Title'] = json_data['data']['entry']['struct']['title']

            # df結合
            Sup_List = pd.concat([Sup_List, df])
        else:
            df = pd.DataFrame(columns=cols)
            empty = []
            empty.append(pdb_id)
            df['PDB_ID'] = empty
            df['RCSB_URL'].iloc[0] =  'https://www.rcsb.org/structure/' + pdb_id
        Sup_List = pd.concat([Sup_List, df])
    else:
        df = pd.DataFrame(columns=cols)
        empty = []
        empty.append(pdb_id)
        df['PDB_ID'] = empty
        df['RCSB_URL'].iloc[0] =  'https://www.rcsb.org/structure/' + pdb_id
        Sup_List = pd.concat([Sup_List, df])

Sup_List = Sup_List.reset_index(drop=True)